[EPIC-1517] Refactor the Public GitHub Examples of RTU UI components
doo/scanbot-sdk-example-ios pull request #37
Opened 2022-01-17 12:23 UTC by Superkachenya

2022-01-19 10:06 UTC, sebastato requested changes

2022-01-19 10:06 UTC, sebastato commented on ReadyToUseUIDemo/Usecases/Data Detect Usecases/UsecaseScanOneDimensionalBarcode.swift
> +        viewController.dismiss(animated: true) {
viewController.presentingViewController?.dismiss(...)

2022-01-19 10:06 UTC, sebastato commented on ReadyToUseUIDemo/Usecases/Data Detect Usecases/UsecaseScanBarcodeBatch.swift
> +        viewController.dismiss(animated: true) {
viewController.presentingViewController?.dismiss(...)

2022-01-19 10:06 UTC, sebastato commented on ReadyToUseUIDemo/Usecases/UsecaseStartWorkflow.swift
> +            viewController.dismiss(animated: true) {
viewController.presentingViewController?.dismiss(...)

2022-01-19 10:06 UTC, sebastato commented on ReadyToUseUIDemo/Generic Document results/GenericDocumentResultListViewController.swift
> +            alert.dismiss(animated: true, completion: nil)
alert.presentingViewController?.dismiss(...)

2022-01-19 10:47 UTC, Superkachenya commented on ReadyToUseUIDemo/Usecases/Data Detect Usecases/UsecaseScanTwoDimensionalBarcode.swift
> +        viewController.dismiss(animated: true) {
This is what I want to do. Dismiss the `SBSDKUIBarcodeScannerViewController`.

2022-01-20 16:39 UTC, sebastato approved these changes

2022-01-20 16:39 UTC, merged